version: "3.9"
services:
  express:
    image: junmop950/jm-total-hub:express-latest
    ports:
      - "5000:5000"
    environment:
      DATABASE_URL: ${DATABASE_URL}
      REDIS_URL: ${REDIS_URL}
      REDIS_PORT: ${REDIS_PORT}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      JWT_SECRET_KEY: ${{ secrets.JWT_SECRET_KEY }}
      JWT_ACCESS_TOKEN_EXPIRATION: ${secrets.JWT_ACCESS_TOKEN_EXPIRATION}
      JWT_REFRESH_TOKEN_EXPIRATION: ${secrets.JWT_REFRESH_TOKEN_EXPIRATION}

  react:
    image: junmop950/jm-total-hub:react-latest
    ports:
      - "3000:3000"
    environment:
      REACT_APP_ENV: ${REACT_APP_ENV}
      REACT_APP_SERVER_IP: ${REACT_APP_SERVER_IP}
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - express
      - react
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    command: redis-server --requirepass ${REDIS_PASSWORD}
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}
