version: "3.9"
services:
  express:
    image: junmop950/jm-total-hub:express-latest
    ports:
      - "5000:5000"
    environment:
      DATABASE_URL: ${DATABASE_URL}
  react:
    image: junmop950/jm-total-hub:react-latest
    ports:
      - "3000:3000"
    environment:
      REACT_APP_EXPRESS_API_URL: ${REACT_APP_EXPRESS_API_URL}
