name: dockercompose ec2 배포

on:
  push:
    branches:
      - main

jobs:
  upload:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: 도커컴포즈 repo git pull
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USERNAME }}
        key: ${{ secrets.EC2_PRIVATE_KEY }}
        script: |
          if [ -d "JMTotalHub-DockerCompose" ]; then
            cd JMTotalHub-DockerCompose
            if [ -d ".git" ]; then
              sudo git pull origin main
            else
              cd ..
              sudo rm -rf JMTotalHub-DockerCompose
              git clone https://github.com/JMTotalHub/JMTotalHub-DockerCompose.git
            fi
          else
            git clone https://github.com/JMTotalHub/JMTotalHub-DockerCompose.git
          fi

    - name: docker compose 구동
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USERNAME }}
        key: ${{ secrets.EC2_PRIVATE_KEY }}
        script: |
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          export DATABASE_URL=${{ secrets.DATABASE_URL }}
          cd JMTotalHub-DockerCompose
          sudo -E docker-compose pull
          sudo -E docker-compose up -d --force-recreate
